

// ACTION TYPE FOR MUSIC DATA
export const GET_MUSIC_RECORD_REQUEST = 'GET_MUSIC_RECORDS_REQUEST';
export const GET_MUSIC_RECORD_SUCCESS = 'GET_MUSIC_RECORDS_SUCCESS';
export const GET_MUSIC_RECORD_FAILURE = 'GET_MUSIC_RECORDS_FAILURE';
