

// ACTION TYPE FOR MUSIC DATA
export const GET_MUSIC_RECORD_REQUEST = 'GET_MUSIC_RECORDS_REQUEST';
export const GET_MUSIC_RECORD_SUCCESS = 'GET_MUSIC_RECORDS_SUCCESS';
export const GET_MUSIC_RECORD_FAILURE = 'GET_MUSIC_RECORDS_FAILURE';


// ACTION TYPE FOR UPDATE MUSIC DATA
export const UPDATE_MUSIC_RECORD_REQUEST = 'UPDATE_MUSIC_RECORDS_REQUEST';
export const UPDATE_MUSIC_RECORD_SUCCESS = 'UPDATE_MUSIC_RECORDS_SUCCESS';
export const UPDATE_MUSIC_RECORD_FAILURE = 'UPDATE_MUSIC_RECORDS_FAILURE';
